# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-27 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('description_img', models.ImageField(blank=True, upload_to='description_images')),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
    ]
