# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-27 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description_img',
            field=models.ImageField(blank=True, upload_to='static/description_images'),
        ),
    ]
