# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-28 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_web', '0003_auto_20160805_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('limittime', models.IntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('process', models.CharField(blank=True, max_length=10, null=True)),
                ('peoplenum', models.IntegerField(blank=True, null=True)),
                ('heatvalue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('decription', models.TextField(blank=True, null=True)),
                ('indexsum', models.IntegerField(blank=True, null=True)),
                ('indextime', models.IntegerField(blank=True, null=True)),
                ('indexrate', models.IntegerField(blank=True, null=True)),
                ('document', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('limittime', models.IntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('process', models.CharField(blank=True, max_length=10, null=True)),
                ('peoplenum', models.IntegerField(blank=True, null=True)),
                ('heatvalue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('decription', models.TextField(blank=True, null=True)),
                ('indexsum', models.IntegerField(blank=True, null=True)),
                ('indextime', models.IntegerField(blank=True, null=True)),
                ('indexrate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'list_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=600, null=True)),
                ('news_url', models.CharField(blank=True, max_length=200, null=True)),
                ('news_part', models.TextField(blank=True, null=True)),
                ('document', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=600, null=True)),
                ('page_keywords', models.CharField(blank=True, max_length=600, null=True)),
                ('page_description', models.TextField(blank=True, null=True)),
                ('news_title', models.CharField(blank=True, max_length=600, null=True)),
                ('news_time', models.TextField(blank=True, null=True)),
                ('news_content', models.TextField(blank=True, null=True)),
                ('news_part', models.TextField(blank=True, null=True)),
                ('news_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'news_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchWebListinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'search_web_listinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpReqinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('count_req', models.IntegerField(blank=True, null=True)),
                ('count_suc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sp_reqinfo',
                'managed': False,
            },
        ),
    ]
